# Python Libraries

## Numpy

#### Used to create multi dimensional arrays

- Creating 1-D aray

In [9]:
import numpy
z=numpy.array([1,2,3,4]) # array is a inbuilt function
print(type(z))
print(z)
#type(z)

<class 'numpy.ndarray'>
[1 2 3 4]


In [15]:
z=numpy.array([1,2,3,4])
a=numpy.array(z)
print(a)
a

[1 2 3 4]


array([1, 2, 3, 4])

- Creating 2-D array

In [13]:
y=numpy.array([[1,2,5,6],[3,4,7,8]])
print(y)

[[1 2 5 6]
 [3 4 7 8]]


- Creating 2-D array

In [23]:
x=numpy.array([[1,2,5,6],[3,4,7,8],[9,10,11,12]])
print(x)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 11 12]
 [ 3  6  7  8]]


In [29]:
print(x[3][0])
print(x.ndim)
print(x.shape)
x.size

3
2
(4, 4)


16

In [44]:
f=numpy.array([[1,[1]],[2,[2]]])
print(f)
f.ndim


[[1 list([1])]
 [2 list([2])]]


<ipython-input-44-10011113443e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  f=numpy.array([[1,[1]],[2,[2]]])


2

In [34]:
t=numpy.array([1,2,3],dtype=complex)
print(t)

[1.+0.j 2.+0.j 3.+0.j]


In [36]:
g=numpy.arange(10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
print(g[:5])
g[::2]
print(g[0:6:2])
print(g[::-1])

[0 1 2 3 4]
[0 2 4]
[9 8 7 6 5 4 3 2 1 0]


## Reshaping of arrayas

In [63]:
s=numpy.arange(0,16).reshape(4,4)
print(s)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [87]:
v=numpy.arange(1000000).reshape(1000,1000)
v

array([[     0,      1,      2, ...,    997,    998,    999],
       [  1000,   1001,   1002, ...,   1997,   1998,   1999],
       [  2000,   2001,   2002, ...,   2997,   2998,   2999],
       ...,
       [997000, 997001, 997002, ..., 997997, 997998, 997999],
       [998000, 998001, 998002, ..., 998997, 998998, 998999],
       [999000, 999001, 999002, ..., 999997, 999998, 999999]])

In [59]:
a=numpy.array([1,2,3])
b=numpy.array([1,2,3])
print(numpy.concatenate([a,b]))
print(sum([a,b]))

[1 2 3 1 2 3]
[2 4 6]


## Splitting of arrays

In [61]:
p=[1,2,3,8,8,3,2,1]
a,b,c=numpy.split(p,[3,6])
print(a,b,c)

[1 2 3] [8 8 3] [2 1]


In [85]:
e=numpy.ones((4,4))
e
e=e-1
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
h=numpy.array([0,1,2,3])
print(numpy.sqrt(h))
print(numpy.sin(h))
print(numpy.cos(h))
print(numpy.tan(h))
a=numpy.random.rand(2,2)
print(a)

[0.         1.         1.41421356 1.73205081]
[0.         0.84147098 0.90929743 0.14112001]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]
[ 0.          1.55740772 -2.18503986 -0.14254654]
[[0.22098992 0.80169652]
 [0.62624802 0.47111493]]


## Filtering Arrays

In [95]:
ar=numpy.array([11,12,13,14])
x=[True,False,True,False]
nar=ar[x]
print(nar)

[11 13]


In [96]:
## Even no.s
ar=numpy.array([1,2,3,4,5,6,7])
f_a=ar%2==0
n_a=ar[f_a]
print(f_a)
print(n_a)

[False  True False  True False  True False]
[2 4 6]


In [97]:
## Odd no.s
ar=numpy.array([1,2,3,4,5,6,7])
f_a=ar%2!=0
n_a=ar[f_a]
print(f_a)
print(n_a)

[ True False  True False  True False  True]
[1 3 5 7]


In [98]:
s=numpy.array([[3,7,5],[8,4,3],[2,4,9]])
print(numpy.amax(s,1))
print(numpy.amax(s,0))
print(numpy.amin(s,1))
print(numpy.amin(s,0))

[7 8 9]
[8 7 9]
[3 3 2]
[2 4 3]
